version: '3.5'

services:
  datastore:
    container_name: dioanalytics-datastore
    image: dioanalytics-datastore
    build:
      context: ./datastore
      dockerfile: dockerfile
    volumes:
      - timelogs:/app/data

  bot:
    container_name: dioanalytics-bot
    image: dioanalytics-bot
    build:
      context: ./bot
      dockerfile: dockerfile
    depends_on:
      - datastore

  # ui:
  # TODO

volumes:
  timelogs:
