version: '3.5'

services:
  datastore:
    container_name: dioanalytics-datastore
    image: dioanalytics-datastore
    build:
      context: ./datastore
      dockerfile: dockerfile
    volumes:
      - ./datastore/data:/app/data

  bot:
    container_name: dioanalytics-bot
    image: dioanalytics-bot
    build:
      context: ./bot
      dockerfile: dockerfile
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_CLIENT_ID
      - TIMELOG_URL=https://discordtimelogs.corydio.com
      - DATASTORE_URL=http://datastore:3001
    depends_on:
      - datastore

  ui:
    container_name: dioanalytics-ui
    image: dioanalytics-ui
    build:
      context: ./ui
      dockerfile: dockerfile
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_CLIENT_ID
      - DATASTORE_URL=http://datastore:3001
    ports:
      - 5173:3000
    depends_on:
      - datastore
